name: Deploy Static Web

on:
  push:
    branches: [main]
    paths:
      - '1-static-web/**'

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_DIR: ./1-static-web/terraform

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    outputs:
      bucket_name: ${{ steps.tf_output.outputs.bucket_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.TF_DIR }}

      - name: Get bucket name
        id: tf_output
        run: echo "bucket_name=$(terraform output -raw bucket_name)" >> $GITHUB_OUTPUT
        working-directory: ${{ env.TF_DIR }}

  deploy:
    name: Deploy files to S3
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Sync to S3
        run: |
          aws s3 sync ./1-static-web/web/ s3://${{ needs.terraform.outputs.bucket_name }}/ \
            --delete \
            --cache-control "max-age=3600"

      - name: Print URL
        run: |
          echo "✅ Web publicada a:"
          echo "http://${{ needs.terraform.outputs.bucket_name }}.s3-website-${{ secrets.AWS_REGION }}.amazonaws.com"
