name: Deploy Static Web

on:
  push:
    branches: [main]
    paths: ['project/1-static-web/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - run: terraform init
        working-directory: ./project/1-static-web/terraform

      - run: terraform apply -auto-approve
        working-directory: ./project/1-static-web/terraform

      - name: Sync fitxers a S3
        run: |
          BUCKET=$(cd ./project/1-static-web/terraform && terraform output -raw bucket_name)
          aws s3 sync ./project/1-static-web/web/ s3://$BUCKET/ --delete

      - name: URL final
        run: |
          cd ./project/1-static-web/terraform
          echo "✅ Web: $(terraform output -raw website_url)"
